apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedme-be
  namespace: feedme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedme-be
  template:
    metadata:
      labels:
        app: feedme-be
    spec:
      initContainers:
        - name: wait-for-mongodb
          image: busybox
          command: ['sh', '-c', 'until nc -z feedme-mongodb 27017; do echo waiting for mongodb; sleep 2; done;']
      containers:
      - name: feedme-be
        image: adhasahar/feedme-sre-backend:latest
        env:
        - name: MONGODB_URL
          value: mongodb://feedme-mongodb:27017
        - name: OTEL_SERVICE_NAME
          value: feedme-backend
        - name: OTEL_SERVICE_VERSION
          value: 1.0.4
        - name: OTEL_EXPORTER_OTLP_COMPRESSION
          value: gzip
        - name: OTEL_TRACES_EXPORTER
          value: otlp
        - name: OTEL_METRICS_EXPORTER
          value: otlp
        - name: OTEL_LOGS_EXPORTER
          value: otlp
        - name: NODE_OPTIONS
          value: --require @opentelemetry/auto-instrumentations-node/register
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=feedme-backend,service.version=1.0.3
        - name: OTEL_NODE_RESOURCE_DETECTORS
          value: all
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "lgtm.observability:4317"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: grpc