apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedme-be
  namespace: feedme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedme-be
  template:
    metadata:
      labels:
        app: feedme-be
    spec:
      initContainers:
        - name: wait-for-mongodb
          image: busybox
          command: ['sh', '-c', 'until nc -z feedme-mongodb 27017; do echo waiting for mongodb; sleep 2; done;']
      containers:
      - name: feedme-be
        image: adhasahar/feedme-sre-backend:latest
        env:
        - name: MONGODB_URL
          value: feedme-mongodb://mongodb:27017