apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment-fe.yaml
- deployment-be.yaml
- deployment-mongodb.yaml
- service-fe.yaml
- service-be.yaml
- service-mongodb.yaml
- ingress-fe.yaml
# - ingress-be.yaml

images:
- name: adhasahar/feedme-sre-frontend
  newTag: 1.0.1
- name: adhasahar/feedme-sre-backend
  newTag: 1.0.1