apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: feedme-be
  name: feedme-be
  namespace: observability
spec:
  endpoints:
    - honorLabels: true
      path: /metrics
      port: http
      scheme: http
      scrapeTimeout: 30s
  jobLabel: feedme-be
  namespaceSelector:
    matchNames:
      - feedme
  selector:
    matchLabels:
      app.kubernetes.io/name: feedme-be
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: feedme-be
  name: feedme-be
  namespace: feedme
spec:
  endpoints:
    - honorLabels: true
      path: /metrics
      port: http
      scheme: http
      scrapeTimeout: 30s
  jobLabel: feedme-be
  namespaceSelector:
    matchNames:
      - feedme
  selector:
    matchLabels:
      app.kubernetes.io/name: feedme-be
