storage:
  trace:
    backend: s3
    s3:
      access_key: 'logs-user'
      secret_key: 'supersecretpassword'
      bucket: 'tempo-traces'
      endpoint: 'loki-minio:9000'
      insecure: true
traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true
  zipkin:
    enabled: false
  jaeger:
    thriftHttp:
      enabled: false
  opencensus:
    enabled: false