grafana:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts: 
      - feedme-grafana.adhshr.xyz
prometheus:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts: 
      - feedme-prometheus.adhshr.xyz