grafana:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts: 
      - feedme-grafana.${hostname}
  # https://grafana.com/docs/grafana/latest/datasources/loki/
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
      jsonData:
        timeout: 60
        maxLines: 1000
prometheus:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts: 
      - feedme-prometheus.${hostname}