server:
  ingress:
    enabled: true
    ingressClassName: "cloudflare-tunnel"
    hostname: feedme-argocd.${hostname}
configs:
  params:
    server.insecure: true
  repositories:
    feedme-sre:
      url: https://github.com/adhasahar97/sre-take-home-assignment
